# SPDX-License-Identifier: MIT

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hamsi"
BBFILE_PATTERN_hamsi = "^${LAYERDIR}/"
BBFILE_PRIORITY_hamsi = "20"

LAYERDEPENDS_hamsi = "core openembedded-layer filesystems-layer networking-layer multimedia-layer gnome-layer meta-python qt6-layer kf6 kde"
LAYERSERIES_COMPAT_hamsi = "wrynose"
